FROM alpine:latest

LABEL maintainer "Kamil Zajac <kaz231@outlook.com>"

ENV APP_DIR "/var/app"
ENV APP_USER "app"
ENV APP_USER_GROUP "app"
ENV COMPOSER_DIR /etc/composer
ENV COMPOSER_FILENAME composer

RUN mkdir -p $APP_DIR

RUN apk update \
    && apk add \
      php7 \
      php7-opcache \
      php7-mbstring \
      php7-curl \
      php7-json \
      php7-intl \
      php7-mcrypt \
      php7-ctype \
      php7-sockets \
      php7-openssl \
      php7-session \
      php7-phar \
      php7-xml \
      ca-certificates \
      openssl \
      su-exec \
    && ln -s /usr/bin/php7 /usr/bin/php \
    && update-ca-certificates \
    && rm -rf /var/cache/apk/*

RUN mkdir $COMPOSER_DIR \
    && wget -O composer-setup.php 'https://getcomposer.org/installer' \
    && php composer-setup.php --install-dir="$COMPOSER_DIR" --filename="$COMPOSER_FILENAME" \
    && rm composer-setup.php \
    && ln -s "$COMPOSER_DIR/$COMPOSER_FILENAME" /usr/bin

COPY entrypoint/dev/docker-entrypoint.sh /usr/local/bin/

VOLUME $APP_DIR
WORKDIR $APP_DIR

ENTRYPOINT [ "docker-entrypoint.sh" ]

CMD ["php"]
